### ISSUE TITLE
EPIC: Lobby

### ISSUE THREAD

**Issue by TheDome0** [SEII-Hexentanz/app#7]
- [x] SEII-Hexentanz/app#6
- [x] SEII-Hexentanz/app#4
- [x] SEII-Hexentanz/app#9
- [x] SEII-Hexentanz/app#10
- [x] SEII-Hexentanz/server#9
